refactor(frontend): hide cta during approve
sifiorg/sifi pull request #404
Opened 2023-11-06 11:07 UTC by tommy0x

### Changes Made

- Hide Approve Button when approving

### Checklist

Please tick the boxes that apply and provide additional details where necessary. Add or edit items as needed.

- [x] Changes are limited to a single goal.
- [x] Responsive design has been tested and looks good on all devices and screen sizes.
- [x] Changes have been tested on all major browsers (Chrome, Firefox, Safari).
- [x] The changes in Chromatic UI Tests all look good.
- [x] No accessibility issues have been introduced in Storybook's Accessibility tab.
- [x] The code has been optimized for performance.

### Related

Closes #391

2023-11-07 18:07 UTC, boriskubrik requested changes
The goal here is to have a single CTA visible at any time. While this PR does achieve it during approving, it hides the wrong CTA.

What we want is to hide the Execute Swap button while the approve button is visible.

![image](https://github.com/sifiorg/sifi/assets/128667801/e2ecf260-e113-4ab4-bc55-12abccdf1edf)

2023-11-16 13:04 UTC, immutablegoblin approved these changes

2023-11-16 13:44 UTC, immutablegoblin commented
Rebasing

2023-11-16 19:14 UTC, boriskubrik approved these changes

2023-11-16 19:14 UTC, merged