feat(frontend): add referral modal
sifiorg/sifi pull request #467
Opened 2023-12-07 13:31 UTC by boriskubrik

- Adds a referral modal. 
- Places links in the Menu and in the footer.
- Fee is set to 2%. UI shows 1% because 50% goes to the protocol.
- Uses context to keep track of the state as we have the modal in multiple places.
- Triggers the share action on mobile, copies to clipboard on desktop.
- Shows toast after successful copy on desktop.
- Shows connect wallet if the user is not connected.

### Testing
- [x] Sharing works on mobile using MetaMask
- [x] Copy works on desktop
- [x] Referral address and fee set in localstorage after using the link
- [x] Connect wallet state works

### Screenshot 
![image](https://github.com/sifiorg/sifi/assets/128667801/85835d6c-91b0-4b83-b8b8-a3b498e89b8f)

2023-12-11 14:52 UTC, tommy0x requested changes

2023-12-11 14:52 UTC, tommy0x commented on packages/frontend/src/modals/ReferralModal/ReferralModal.tsx
> +    const feeBps = 20;
This should be 200 if I'm correct. 1 BPS is 0.01%

2023-12-11 15:03 UTC, immutablegoblin reviewed
Looks good, just needs bps adjustment as noted by Tommy

2023-12-11 20:28 UTC, boriskubrik commented
Need to hold on until the URL structure is finalized. #479

2023-12-12 03:21 UTC, xykota commented
Let's make this ref link not include the fee bps. Then we'll have the default fee when there is a partner at 40 bps and without a partner 20 bps.

Then in the next iteration we will let the user customize the fee bps and reflect in the text they are sharing it down the middle with the protocol.

ref #479

2024-01-22 21:31 UTC, boriskubrik commented
Rebased, updated the URL, tested and it works. Ready for review.

![image](https://github.com/sifiorg/sifi/assets/128667801/c059c542-c707-4001-9957-c160b2b21030)

2024-01-23 14:26 UTC, immutablegoblin commented
It would be nice not to have the linebreak when the modal is at full width if possible?

Working well though.

![image](https://github.com/sifiorg/sifi/assets/112887817/3180211e-aa82-4e7c-b3f9-3c985b577419)

2024-01-24 14:41 UTC, boriskubrik commented
@immutablegoblin switched to `break-all`.

![image](https://github.com/sifiorg/sifi/assets/128667801/3a16d825-7797-416a-bab3-0ecfb2e9c0c5)

2024-01-24 15:07 UTC, immutablegoblin approved these changes

2024-01-24 15:24 UTC, merged