fix(frontend): temp "loading" Toast type
sifiorg/sifi pull request #506
Opened 2023-12-23 13:18 UTC by boriskubrik

Can't figure out why the "loading" prop is not working. `ToastType` clearly contains it and the shared-ui build looks fine. It works when passed directly to `Toast`, but not when used in `showToast`.

This PR temporary fixes it so that we can continue deploying.

2023-12-23 14:15 UTC, xykota requested changes
The `type` field exists on both `ToastProps` and `ToastOptions`. The latter uses `type` of `TypeOptions` which does not have `loading`. You may be able to do `ToastOptions & ToastProps` to override the other way around, or `Omit<ToastOptions, 'type'>`

2023-12-23 17:11 UTC, boriskubrik commented
Thanks, @xykota!

Fixed the `type` issue by omitting `type` from `ToastOptions` in the latest `shared-ui` build. Should be good now.

2023-12-24 09:59 UTC, xykota commented
Rebased to remove the two commits that cancel out

2023-12-24 10:14 UTC, xykota approved these changes

2023-12-24 10:14 UTC, merged