feat(frontend): use the Sifi API for getting token balances
sifiorg/sifi pull request #527
Opened 2024-01-26 18:43 UTC by boriskubrik

2024-02-06 05:42 UTC, xykota submitted a review, later dismissed
Minor

2024-02-06 05:42 UTC, xykota commented on packages/frontend/src/providers/WalletBalancesProvider.tsx
> +            balances.forEach(balance => {
```typescript
const newBalanceMapsByChain = balances.reduce<Record<number, BalanceMap>>((acc, balance), {
  if (!balance) {
    console...
    return acc;
  }

  const map = acc[chainId] ?? new Map();

  map.set(...);

  return {
    ...acc,
    [chainId]: map,
  };
}, {});
```

2024-02-06 08:54 UTC, immutablegoblin requested changes
Pretty heavy console spamming from failed Coingecko lookups here

![image](https://github.com/sifiorg/sifi/assets/112887817/6b1f37c7-26bc-4458-9d42-180a008115ce)

We should probably handle these better by aggregating or suppressing them, going to make debugging a chore in the future.

2024-02-06 09:12 UTC, immutablegoblin commented
I also can't work out whats going on here but something isn't right:

When I switch to Avalance we're trying to run `balanceOf` on this contract, but it's not a token - is this one of ours?

https://etherscan.io/address/0x2791bca1f2de4661ed88a30c99a7a9449aa84174#multichain-portfolio

My understanding is we're only supposed to be running `balanceOf` directly on the currently selected `to` and `from` tokens for the most up to date balance, so this seems unexpected.

2024-02-06 09:15 UTC, immutablegoblin commented
Oh I think I worked it out.

Currently if you change networks it will take the previously selected token and then try and fetch the balance for the _old token address on the new network_ resulting in a failure.

2024-02-06 19:23 UTC, boriskubrik commented
@immutablegoblin I've suppressed the Coingecko errors.  [e3bd912](https://github.com/sifiorg/sifi/pull/527/commits/e3bd9123486483d03512e81378392b0d1718b3d0) 

We still see errors from the SDK, but it is a separate matter.

2024-02-07 10:09 UTC, immutablegoblin approved these changes

2024-02-07 10:52 UTC, merged